- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Set default incoming policy to deny
  ufw:
    policy: deny
    direction: incoming

- name: Allow SSH (port 22)
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow HTTP (port 80)
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled

